version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ai_ui_generator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
      - ai-service
    environment:
      - CONFIG_PATH=/app/configs/config.yaml

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      - CONFIG_PATH=/app/configs/config.yaml

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - CONFIG_PATH=/app/configs/config.yaml

  ai-service:
    build:
      context: .
      dockerfile: Dockerfile.ai
    ports:
      - "8083:8083"
    environment:
      - CONFIG_PATH=/app/configs/config.yaml

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080

volumes:
  postgres_data:
