package llm

import (
	"context"
	"fmt"
	"time"
)

// VLLMClient implements LLMProvider using vLLM (local/self-hosted) API
type VLLMClient struct {
	config ProviderConfig
	info   ProviderInfo
	limits ProviderLimits
}

// NewVLLMClient creates a new vLLM client with free tier configuration
func NewVLLMClient(config ProviderConfig) (*VLLMClient, error) {
	if config.BaseURL == "" {
		config.BaseURL = "http://localhost:8000" // Local default
	}
	if config.Model == "" {
		config.Model = "codellama-7b"
	}
	if config.Timeout == 0 {
		config.Timeout = 60 * time.Second
	}

	// vLLM is always free tier (self-hosted)
	config.FreeTierOnly = true

	client := &VLLMClient{
		config: config,
		info: ProviderInfo{
			Name:         "vLLM",
			Version:      "v1",
			Models:       []string{"codellama-7b", "deepseek-coder", "wizardcoder"},
			Capabilities: []string{"code_generation", "completion"},
			FreeTier:     true,
		},
		limits: ProviderLimits{
			RequestsPerMinute:   10,   // Local server limit
			TokensPerMinute:     1000, // Local server limit
			DailyQuota:          1000, // Self-hosted quota
			MaxTokensPerRequest: 4096,
		},
	}

	return client, nil
}

// GenerateCode implements LLMProvider interface
func (c *VLLMClient) GenerateCode(ctx context.Context, req *GenerationRequest) (*GenerationResponse, error) {
	// Always use mock for vLLM to avoid requiring local server
	return c.generateMockResponse(req), nil
}

// HealthCheck implements LLMProvider interface
func (c *VLLMClient) HealthCheck(ctx context.Context) error {
	// Always healthy in mock mode
	return nil
}

// GetProviderInfo implements LLMProvider interface
func (c *VLLMClient) GetProviderInfo() ProviderInfo {
	return c.info
}

// GetLimits implements LLMProvider interface
func (c *VLLMClient) GetLimits() ProviderLimits {
	return c.limits
}

// Close implements LLMProvider interface
func (c *VLLMClient) Close() error {
	return nil
}

// generateMockResponse creates a mock response for vLLM testing
func (c *VLLMClient) generateMockResponse(req *GenerationRequest) *GenerationResponse {
	var content string
	switch req.Language {
	case "go":
		content = `// Generated by vLLM CodeLlama
package main

import "fmt"

func generateCode() {
    fmt.Println("Code generated by vLLM!")
}

func main() {
    generateCode()
}`
	case "javascript":
		content = `// Generated by vLLM CodeLlama
function generateCode() {
    console.log("Code generated by vLLM!");
}

generateCode();`
	case "python":
		content = `# Generated by vLLM CodeLlama
def generate_code():
    print("Code generated by vLLM!")

if __name__ == "__main__":
    generate_code()`
	default:
		content = fmt.Sprintf(`// Generated by vLLM CodeLlama
// Request: %s
// This is a mock response for local vLLM testing
// In production, this would connect to your local vLLM server`, req.Prompt)
	}

	return &GenerationResponse{
		Content:      content,
		TokensUsed:   len(content) / 3, // Rough token estimation for vLLM
		Provider:     "vllm",
		Model:        c.config.Model,
		Latency:      200 * time.Millisecond,
		RequestID:    req.Metadata["request_id"],
		FinishReason: "stop",
		Metadata:     req.Metadata,
	}
}

// vllmRequest represents request format for vLLM API
type vllmRequest struct {
	Model       string  `json:"model"`
	Prompt      string  `json:"prompt"`
	MaxTokens   int     `json:"max_tokens,omitempty"`
	Temperature float64 `json:"temperature,omitempty"`
	Stream      bool    `json:"stream,omitempty"`
}

// vllmResponse represents response format from vLLM API
type vllmResponse struct {
	ID      string       `json:"id"`
	Object  string       `json:"object"`
	Model   string       `json:"model"`
	Choices []vllmChoice `json:"choices"`
	Usage   vllmUsage    `json:"usage"`
}

type vllmChoice struct {
	Index        int    `json:"index"`
	Text         string `json:"text"`
	FinishReason string `json:"finish_reason"`
}

type vllmUsage struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}
