// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ai/llm_abstractor.go
//
// Generated by this command:
//
//	mockgen -source=internal/ai/llm_abstractor.go -destination=tests/mocks/ai_service_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLLMClient is a mock of LLMClient interface.
type MockLLMClient struct {
	ctrl     *gomock.Controller
	recorder *MockLLMClientMockRecorder
	isgomock struct{}
}

// MockLLMClientMockRecorder is the mock recorder for MockLLMClient.
type MockLLMClientMockRecorder struct {
	mock *MockLLMClient
}

// NewMockLLMClient creates a new mock instance.
func NewMockLLMClient(ctrl *gomock.Controller) *MockLLMClient {
	mock := &MockLLMClient{ctrl: ctrl}
	mock.recorder = &MockLLMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMClient) EXPECT() *MockLLMClientMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockLLMClient) Generate(prompt string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", prompt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockLLMClientMockRecorder) Generate(prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockLLMClient)(nil).Generate), prompt)
}

// StreamGenerate mocks base method.
func (m *MockLLMClient) StreamGenerate(prompt string, responseChannel chan string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamGenerate", prompt, responseChannel)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamGenerate indicates an expected call of StreamGenerate.
func (mr *MockLLMClientMockRecorder) StreamGenerate(prompt, responseChannel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamGenerate", reflect.TypeOf((*MockLLMClient)(nil).StreamGenerate), prompt, responseChannel)
}
