// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ai/llm/builder.go
//
// Generated by this command:
//
//	mockgen -source=internal/ai/llm/builder.go -destination=tests/mocks/builder_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	llm "github.com/EliasRanz/ai-code-gen/internal/ai/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockGenerationRequestBuilder is a mock of GenerationRequestBuilder interface.
type MockGenerationRequestBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockGenerationRequestBuilderMockRecorder
	isgomock struct{}
}

// MockGenerationRequestBuilderMockRecorder is the mock recorder for MockGenerationRequestBuilder.
type MockGenerationRequestBuilderMockRecorder struct {
	mock *MockGenerationRequestBuilder
}

// NewMockGenerationRequestBuilder creates a new mock instance.
func NewMockGenerationRequestBuilder(ctrl *gomock.Controller) *MockGenerationRequestBuilder {
	mock := &MockGenerationRequestBuilder{ctrl: ctrl}
	mock.recorder = &MockGenerationRequestBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerationRequestBuilder) EXPECT() *MockGenerationRequestBuilderMockRecorder {
	return m.recorder
}

// AddMetadata mocks base method.
func (m *MockGenerationRequestBuilder) AddMetadata(key, value string) llm.GenerationRequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMetadata", key, value)
	ret0, _ := ret[0].(llm.GenerationRequestBuilder)
	return ret0
}

// AddMetadata indicates an expected call of AddMetadata.
func (mr *MockGenerationRequestBuilderMockRecorder) AddMetadata(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMetadata", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).AddMetadata), key, value)
}

// Build mocks base method.
func (m *MockGenerationRequestBuilder) Build() (*llm.GenerationRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build")
	ret0, _ := ret[0].(*llm.GenerationRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockGenerationRequestBuilderMockRecorder) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).Build))
}

// EnableStreaming mocks base method.
func (m *MockGenerationRequestBuilder) EnableStreaming() llm.GenerationRequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableStreaming")
	ret0, _ := ret[0].(llm.GenerationRequestBuilder)
	return ret0
}

// EnableStreaming indicates an expected call of EnableStreaming.
func (mr *MockGenerationRequestBuilderMockRecorder) EnableStreaming() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableStreaming", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).EnableStreaming))
}

// SetLanguage mocks base method.
func (m *MockGenerationRequestBuilder) SetLanguage(language string) llm.GenerationRequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLanguage", language)
	ret0, _ := ret[0].(llm.GenerationRequestBuilder)
	return ret0
}

// SetLanguage indicates an expected call of SetLanguage.
func (mr *MockGenerationRequestBuilderMockRecorder) SetLanguage(language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLanguage", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).SetLanguage), language)
}

// SetMaxTokens mocks base method.
func (m *MockGenerationRequestBuilder) SetMaxTokens(tokens int) llm.GenerationRequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMaxTokens", tokens)
	ret0, _ := ret[0].(llm.GenerationRequestBuilder)
	return ret0
}

// SetMaxTokens indicates an expected call of SetMaxTokens.
func (mr *MockGenerationRequestBuilderMockRecorder) SetMaxTokens(tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxTokens", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).SetMaxTokens), tokens)
}

// SetModel mocks base method.
func (m *MockGenerationRequestBuilder) SetModel(model string) llm.GenerationRequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetModel", model)
	ret0, _ := ret[0].(llm.GenerationRequestBuilder)
	return ret0
}

// SetModel indicates an expected call of SetModel.
func (mr *MockGenerationRequestBuilderMockRecorder) SetModel(model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetModel", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).SetModel), model)
}

// SetPrompt mocks base method.
func (m *MockGenerationRequestBuilder) SetPrompt(prompt string) llm.GenerationRequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrompt", prompt)
	ret0, _ := ret[0].(llm.GenerationRequestBuilder)
	return ret0
}

// SetPrompt indicates an expected call of SetPrompt.
func (mr *MockGenerationRequestBuilderMockRecorder) SetPrompt(prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrompt", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).SetPrompt), prompt)
}

// SetProvider mocks base method.
func (m *MockGenerationRequestBuilder) SetProvider(provider string) llm.GenerationRequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProvider", provider)
	ret0, _ := ret[0].(llm.GenerationRequestBuilder)
	return ret0
}

// SetProvider indicates an expected call of SetProvider.
func (mr *MockGenerationRequestBuilderMockRecorder) SetProvider(provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProvider", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).SetProvider), provider)
}

// SetTemperature mocks base method.
func (m *MockGenerationRequestBuilder) SetTemperature(temp float64) llm.GenerationRequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTemperature", temp)
	ret0, _ := ret[0].(llm.GenerationRequestBuilder)
	return ret0
}

// SetTemperature indicates an expected call of SetTemperature.
func (mr *MockGenerationRequestBuilderMockRecorder) SetTemperature(temp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTemperature", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).SetTemperature), temp)
}

// SetTimeout mocks base method.
func (m *MockGenerationRequestBuilder) SetTimeout(timeout time.Duration) llm.GenerationRequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTimeout", timeout)
	ret0, _ := ret[0].(llm.GenerationRequestBuilder)
	return ret0
}

// SetTimeout indicates an expected call of SetTimeout.
func (mr *MockGenerationRequestBuilderMockRecorder) SetTimeout(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimeout", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).SetTimeout), timeout)
}

// SetUserID mocks base method.
func (m *MockGenerationRequestBuilder) SetUserID(userID string) llm.GenerationRequestBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserID", userID)
	ret0, _ := ret[0].(llm.GenerationRequestBuilder)
	return ret0
}

// SetUserID indicates an expected call of SetUserID.
func (mr *MockGenerationRequestBuilderMockRecorder) SetUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserID", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).SetUserID), userID)
}

// Validate mocks base method.
func (m *MockGenerationRequestBuilder) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockGenerationRequestBuilderMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockGenerationRequestBuilder)(nil).Validate))
}
