// Code generated by MockGen. DO NOT EDIT.
// Source: internal/cache/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/cache/interfaces.go -destination=tests/mocks/cache_mocks.go -package=mocks -mock_names=HealthOperations=MockCacheHealthOperations
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	cache "github.com/EliasRanz/ai-code-gen/internal/cache"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheProvider is a mock of CacheProvider interface.
type MockCacheProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCacheProviderMockRecorder
	isgomock struct{}
}

// MockCacheProviderMockRecorder is the mock recorder for MockCacheProvider.
type MockCacheProviderMockRecorder struct {
	mock *MockCacheProvider
}

// NewMockCacheProvider creates a new mock instance.
func NewMockCacheProvider(ctrl *gomock.Controller) *MockCacheProvider {
	mock := &MockCacheProvider{ctrl: ctrl}
	mock.recorder = &MockCacheProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheProvider) EXPECT() *MockCacheProviderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCacheProvider) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCacheProviderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCacheProvider)(nil).Close))
}

// Delete mocks base method.
func (m *MockCacheProvider) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheProviderMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheProvider)(nil).Delete), ctx, key)
}

// DeleteByPattern mocks base method.
func (m *MockCacheProvider) DeleteByPattern(ctx context.Context, pattern string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPattern", ctx, pattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPattern indicates an expected call of DeleteByPattern.
func (mr *MockCacheProviderMockRecorder) DeleteByPattern(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPattern", reflect.TypeOf((*MockCacheProvider)(nil).DeleteByPattern), ctx, pattern)
}

// Exists mocks base method.
func (m *MockCacheProvider) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockCacheProviderMockRecorder) Exists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockCacheProvider)(nil).Exists), ctx, key)
}

// Get mocks base method.
func (m *MockCacheProvider) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheProviderMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheProvider)(nil).Get), ctx, key)
}

// HealthCheck mocks base method.
func (m *MockCacheProvider) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockCacheProviderMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockCacheProvider)(nil).HealthCheck), ctx)
}

// Keys mocks base method.
func (m *MockCacheProvider) Keys(ctx context.Context, pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys", ctx, pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Keys indicates an expected call of Keys.
func (mr *MockCacheProviderMockRecorder) Keys(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockCacheProvider)(nil).Keys), ctx, pattern)
}

// MDelete mocks base method.
func (m *MockCacheProvider) MDelete(ctx context.Context, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MDelete", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// MDelete indicates an expected call of MDelete.
func (mr *MockCacheProviderMockRecorder) MDelete(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MDelete", reflect.TypeOf((*MockCacheProvider)(nil).MDelete), ctx, keys)
}

// MGet mocks base method.
func (m *MockCacheProvider) MGet(ctx context.Context, keys []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MGet", ctx, keys)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGet indicates an expected call of MGet.
func (mr *MockCacheProviderMockRecorder) MGet(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGet", reflect.TypeOf((*MockCacheProvider)(nil).MGet), ctx, keys)
}

// MSet mocks base method.
func (m *MockCacheProvider) MSet(ctx context.Context, pairs map[string]string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MSet", ctx, pairs, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// MSet indicates an expected call of MSet.
func (mr *MockCacheProviderMockRecorder) MSet(ctx, pairs, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MSet", reflect.TypeOf((*MockCacheProvider)(nil).MSet), ctx, pairs, ttl)
}

// Set mocks base method.
func (m *MockCacheProvider) Set(ctx context.Context, key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheProviderMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheProvider)(nil).Set), ctx, key, value, ttl)
}

// MockBasicCacheOperations is a mock of BasicCacheOperations interface.
type MockBasicCacheOperations struct {
	ctrl     *gomock.Controller
	recorder *MockBasicCacheOperationsMockRecorder
	isgomock struct{}
}

// MockBasicCacheOperationsMockRecorder is the mock recorder for MockBasicCacheOperations.
type MockBasicCacheOperationsMockRecorder struct {
	mock *MockBasicCacheOperations
}

// NewMockBasicCacheOperations creates a new mock instance.
func NewMockBasicCacheOperations(ctrl *gomock.Controller) *MockBasicCacheOperations {
	mock := &MockBasicCacheOperations{ctrl: ctrl}
	mock.recorder = &MockBasicCacheOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasicCacheOperations) EXPECT() *MockBasicCacheOperationsMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBasicCacheOperations) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBasicCacheOperationsMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBasicCacheOperations)(nil).Delete), ctx, key)
}

// Exists mocks base method.
func (m *MockBasicCacheOperations) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockBasicCacheOperationsMockRecorder) Exists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockBasicCacheOperations)(nil).Exists), ctx, key)
}

// Get mocks base method.
func (m *MockBasicCacheOperations) Get(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBasicCacheOperationsMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBasicCacheOperations)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockBasicCacheOperations) Set(ctx context.Context, key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockBasicCacheOperationsMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockBasicCacheOperations)(nil).Set), ctx, key, value, ttl)
}

// MockBatchCacheOperations is a mock of BatchCacheOperations interface.
type MockBatchCacheOperations struct {
	ctrl     *gomock.Controller
	recorder *MockBatchCacheOperationsMockRecorder
	isgomock struct{}
}

// MockBatchCacheOperationsMockRecorder is the mock recorder for MockBatchCacheOperations.
type MockBatchCacheOperationsMockRecorder struct {
	mock *MockBatchCacheOperations
}

// NewMockBatchCacheOperations creates a new mock instance.
func NewMockBatchCacheOperations(ctrl *gomock.Controller) *MockBatchCacheOperations {
	mock := &MockBatchCacheOperations{ctrl: ctrl}
	mock.recorder = &MockBatchCacheOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchCacheOperations) EXPECT() *MockBatchCacheOperationsMockRecorder {
	return m.recorder
}

// MDelete mocks base method.
func (m *MockBatchCacheOperations) MDelete(ctx context.Context, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MDelete", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// MDelete indicates an expected call of MDelete.
func (mr *MockBatchCacheOperationsMockRecorder) MDelete(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MDelete", reflect.TypeOf((*MockBatchCacheOperations)(nil).MDelete), ctx, keys)
}

// MGet mocks base method.
func (m *MockBatchCacheOperations) MGet(ctx context.Context, keys []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MGet", ctx, keys)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MGet indicates an expected call of MGet.
func (mr *MockBatchCacheOperationsMockRecorder) MGet(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MGet", reflect.TypeOf((*MockBatchCacheOperations)(nil).MGet), ctx, keys)
}

// MSet mocks base method.
func (m *MockBatchCacheOperations) MSet(ctx context.Context, pairs map[string]string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MSet", ctx, pairs, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// MSet indicates an expected call of MSet.
func (mr *MockBatchCacheOperationsMockRecorder) MSet(ctx, pairs, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MSet", reflect.TypeOf((*MockBatchCacheOperations)(nil).MSet), ctx, pairs, ttl)
}

// MockPatternCacheOperations is a mock of PatternCacheOperations interface.
type MockPatternCacheOperations struct {
	ctrl     *gomock.Controller
	recorder *MockPatternCacheOperationsMockRecorder
	isgomock struct{}
}

// MockPatternCacheOperationsMockRecorder is the mock recorder for MockPatternCacheOperations.
type MockPatternCacheOperationsMockRecorder struct {
	mock *MockPatternCacheOperations
}

// NewMockPatternCacheOperations creates a new mock instance.
func NewMockPatternCacheOperations(ctrl *gomock.Controller) *MockPatternCacheOperations {
	mock := &MockPatternCacheOperations{ctrl: ctrl}
	mock.recorder = &MockPatternCacheOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatternCacheOperations) EXPECT() *MockPatternCacheOperationsMockRecorder {
	return m.recorder
}

// DeleteByPattern mocks base method.
func (m *MockPatternCacheOperations) DeleteByPattern(ctx context.Context, pattern string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPattern", ctx, pattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPattern indicates an expected call of DeleteByPattern.
func (mr *MockPatternCacheOperationsMockRecorder) DeleteByPattern(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPattern", reflect.TypeOf((*MockPatternCacheOperations)(nil).DeleteByPattern), ctx, pattern)
}

// Keys mocks base method.
func (m *MockPatternCacheOperations) Keys(ctx context.Context, pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys", ctx, pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Keys indicates an expected call of Keys.
func (mr *MockPatternCacheOperationsMockRecorder) Keys(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockPatternCacheOperations)(nil).Keys), ctx, pattern)
}

// MockCacheHealthOperations is a mock of HealthOperations interface.
type MockCacheHealthOperations struct {
	ctrl     *gomock.Controller
	recorder *MockCacheHealthOperationsMockRecorder
	isgomock struct{}
}

// MockCacheHealthOperationsMockRecorder is the mock recorder for MockCacheHealthOperations.
type MockCacheHealthOperationsMockRecorder struct {
	mock *MockCacheHealthOperations
}

// NewMockCacheHealthOperations creates a new mock instance.
func NewMockCacheHealthOperations(ctrl *gomock.Controller) *MockCacheHealthOperations {
	mock := &MockCacheHealthOperations{ctrl: ctrl}
	mock.recorder = &MockCacheHealthOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheHealthOperations) EXPECT() *MockCacheHealthOperationsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCacheHealthOperations) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCacheHealthOperationsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCacheHealthOperations)(nil).Close))
}

// HealthCheck mocks base method.
func (m *MockCacheHealthOperations) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockCacheHealthOperationsMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockCacheHealthOperations)(nil).HealthCheck), ctx)
}

// MockCacheFactory is a mock of CacheFactory interface.
type MockCacheFactory struct {
	ctrl     *gomock.Controller
	recorder *MockCacheFactoryMockRecorder
	isgomock struct{}
}

// MockCacheFactoryMockRecorder is the mock recorder for MockCacheFactory.
type MockCacheFactoryMockRecorder struct {
	mock *MockCacheFactory
}

// NewMockCacheFactory creates a new mock instance.
func NewMockCacheFactory(ctrl *gomock.Controller) *MockCacheFactory {
	mock := &MockCacheFactory{ctrl: ctrl}
	mock.recorder = &MockCacheFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheFactory) EXPECT() *MockCacheFactoryMockRecorder {
	return m.recorder
}

// CreateProvider mocks base method.
func (m *MockCacheFactory) CreateProvider(providerType string, config cache.CacheConfig) (cache.CacheProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProvider", providerType, config)
	ret0, _ := ret[0].(cache.CacheProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProvider indicates an expected call of CreateProvider.
func (mr *MockCacheFactoryMockRecorder) CreateProvider(providerType, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProvider", reflect.TypeOf((*MockCacheFactory)(nil).CreateProvider), providerType, config)
}

// ListAvailableProviders mocks base method.
func (m *MockCacheFactory) ListAvailableProviders() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableProviders")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListAvailableProviders indicates an expected call of ListAvailableProviders.
func (mr *MockCacheFactoryMockRecorder) ListAvailableProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableProviders", reflect.TypeOf((*MockCacheFactory)(nil).ListAvailableProviders))
}

// MockCacheMetrics is a mock of CacheMetrics interface.
type MockCacheMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMetricsMockRecorder
	isgomock struct{}
}

// MockCacheMetricsMockRecorder is the mock recorder for MockCacheMetrics.
type MockCacheMetricsMockRecorder struct {
	mock *MockCacheMetrics
}

// NewMockCacheMetrics creates a new mock instance.
func NewMockCacheMetrics(ctrl *gomock.Controller) *MockCacheMetrics {
	mock := &MockCacheMetrics{ctrl: ctrl}
	mock.recorder = &MockCacheMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheMetrics) EXPECT() *MockCacheMetricsMockRecorder {
	return m.recorder
}

// IncrementError mocks base method.
func (m *MockCacheMetrics) IncrementError(provider, operation string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementError", provider, operation)
}

// IncrementError indicates an expected call of IncrementError.
func (mr *MockCacheMetricsMockRecorder) IncrementError(provider, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementError", reflect.TypeOf((*MockCacheMetrics)(nil).IncrementError), provider, operation)
}

// IncrementHit mocks base method.
func (m *MockCacheMetrics) IncrementHit(provider, operation string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementHit", provider, operation)
}

// IncrementHit indicates an expected call of IncrementHit.
func (mr *MockCacheMetricsMockRecorder) IncrementHit(provider, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementHit", reflect.TypeOf((*MockCacheMetrics)(nil).IncrementHit), provider, operation)
}

// IncrementMiss mocks base method.
func (m *MockCacheMetrics) IncrementMiss(provider, operation string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementMiss", provider, operation)
}

// IncrementMiss indicates an expected call of IncrementMiss.
func (mr *MockCacheMetricsMockRecorder) IncrementMiss(provider, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementMiss", reflect.TypeOf((*MockCacheMetrics)(nil).IncrementMiss), provider, operation)
}

// RecordLatency mocks base method.
func (m *MockCacheMetrics) RecordLatency(provider, operation string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordLatency", provider, operation, duration)
}

// RecordLatency indicates an expected call of RecordLatency.
func (mr *MockCacheMetricsMockRecorder) RecordLatency(provider, operation, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordLatency", reflect.TypeOf((*MockCacheMetrics)(nil).RecordLatency), provider, operation, duration)
}

// MockServiceCacheManager is a mock of ServiceCacheManager interface.
type MockServiceCacheManager struct {
	ctrl     *gomock.Controller
	recorder *MockServiceCacheManagerMockRecorder
	isgomock struct{}
}

// MockServiceCacheManagerMockRecorder is the mock recorder for MockServiceCacheManager.
type MockServiceCacheManagerMockRecorder struct {
	mock *MockServiceCacheManager
}

// NewMockServiceCacheManager creates a new mock instance.
func NewMockServiceCacheManager(ctrl *gomock.Controller) *MockServiceCacheManager {
	mock := &MockServiceCacheManager{ctrl: ctrl}
	mock.recorder = &MockServiceCacheManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceCacheManager) EXPECT() *MockServiceCacheManagerMockRecorder {
	return m.recorder
}

// GenerateKey mocks base method.
func (m *MockServiceCacheManager) GenerateKey(keyType string, identifiers ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{keyType}
	for _, a := range identifiers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateKey", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateKey indicates an expected call of GenerateKey.
func (mr *MockServiceCacheManagerMockRecorder) GenerateKey(keyType any, identifiers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{keyType}, identifiers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKey", reflect.TypeOf((*MockServiceCacheManager)(nil).GenerateKey), varargs...)
}

// GetJSON mocks base method.
func (m *MockServiceCacheManager) GetJSON(ctx context.Context, key string, target any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSON", ctx, key, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetJSON indicates an expected call of GetJSON.
func (mr *MockServiceCacheManagerMockRecorder) GetJSON(ctx, key, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSON", reflect.TypeOf((*MockServiceCacheManager)(nil).GetJSON), ctx, key, target)
}

// HealthCheck mocks base method.
func (m *MockServiceCacheManager) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockServiceCacheManagerMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockServiceCacheManager)(nil).HealthCheck), ctx)
}

// InvalidateByPattern mocks base method.
func (m *MockServiceCacheManager) InvalidateByPattern(ctx context.Context, pattern string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByPattern", ctx, pattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByPattern indicates an expected call of InvalidateByPattern.
func (mr *MockServiceCacheManagerMockRecorder) InvalidateByPattern(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByPattern", reflect.TypeOf((*MockServiceCacheManager)(nil).InvalidateByPattern), ctx, pattern)
}

// InvalidateByUser mocks base method.
func (m *MockServiceCacheManager) InvalidateByUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByUser indicates an expected call of InvalidateByUser.
func (mr *MockServiceCacheManagerMockRecorder) InvalidateByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByUser", reflect.TypeOf((*MockServiceCacheManager)(nil).InvalidateByUser), ctx, userID)
}

// SetJSON mocks base method.
func (m *MockServiceCacheManager) SetJSON(ctx context.Context, key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJSON", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJSON indicates an expected call of SetJSON.
func (mr *MockServiceCacheManagerMockRecorder) SetJSON(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJSON", reflect.TypeOf((*MockServiceCacheManager)(nil).SetJSON), ctx, key, value, ttl)
}
