// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/interfaces.go -destination=tests/mocks/config_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	config "github.com/EliasRanz/ai-code-gen/internal/config"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigProvider is a mock of ConfigProvider interface.
type MockConfigProvider struct {
	ctrl     *gomock.Controller
	recorder *MockConfigProviderMockRecorder
	isgomock struct{}
}

// MockConfigProviderMockRecorder is the mock recorder for MockConfigProvider.
type MockConfigProviderMockRecorder struct {
	mock *MockConfigProvider
}

// NewMockConfigProvider creates a new mock instance.
func NewMockConfigProvider(ctrl *gomock.Controller) *MockConfigProvider {
	mock := &MockConfigProvider{ctrl: ctrl}
	mock.recorder = &MockConfigProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigProvider) EXPECT() *MockConfigProviderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConfigProvider) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConfigProviderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConfigProvider)(nil).Close))
}

// Get mocks base method.
func (m *MockConfigProvider) Get(ctx context.Context, key string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConfigProviderMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigProvider)(nil).Get), ctx, key)
}

// HealthCheck mocks base method.
func (m *MockConfigProvider) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockConfigProviderMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockConfigProvider)(nil).HealthCheck), ctx)
}

// Load mocks base method.
func (m *MockConfigProvider) Load(ctx context.Context) (config.ConfigData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx)
	ret0, _ := ret[0].(config.ConfigData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockConfigProviderMockRecorder) Load(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockConfigProvider)(nil).Load), ctx)
}

// Validate mocks base method.
func (m *MockConfigProvider) Validate(ctx context.Context, data config.ConfigData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockConfigProviderMockRecorder) Validate(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockConfigProvider)(nil).Validate), ctx, data)
}

// Watch mocks base method.
func (m *MockConfigProvider) Watch(ctx context.Context, callback func(config.ConfigData)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockConfigProviderMockRecorder) Watch(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockConfigProvider)(nil).Watch), ctx, callback)
}

// MockConfigFactory is a mock of ConfigFactory interface.
type MockConfigFactory struct {
	ctrl     *gomock.Controller
	recorder *MockConfigFactoryMockRecorder
	isgomock struct{}
}

// MockConfigFactoryMockRecorder is the mock recorder for MockConfigFactory.
type MockConfigFactoryMockRecorder struct {
	mock *MockConfigFactory
}

// NewMockConfigFactory creates a new mock instance.
func NewMockConfigFactory(ctrl *gomock.Controller) *MockConfigFactory {
	mock := &MockConfigFactory{ctrl: ctrl}
	mock.recorder = &MockConfigFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigFactory) EXPECT() *MockConfigFactoryMockRecorder {
	return m.recorder
}

// CreateProvider mocks base method.
func (m *MockConfigFactory) CreateProvider(providerType, source string) (config.ConfigProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProvider", providerType, source)
	ret0, _ := ret[0].(config.ConfigProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProvider indicates an expected call of CreateProvider.
func (mr *MockConfigFactoryMockRecorder) CreateProvider(providerType, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProvider", reflect.TypeOf((*MockConfigFactory)(nil).CreateProvider), providerType, source)
}

// ListAvailableProviders mocks base method.
func (m *MockConfigFactory) ListAvailableProviders() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableProviders")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListAvailableProviders indicates an expected call of ListAvailableProviders.
func (mr *MockConfigFactoryMockRecorder) ListAvailableProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableProviders", reflect.TypeOf((*MockConfigFactory)(nil).ListAvailableProviders))
}

// RegisterProvider mocks base method.
func (m *MockConfigFactory) RegisterProvider(providerType string, factory config.ProviderFactory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterProvider", providerType, factory)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterProvider indicates an expected call of RegisterProvider.
func (mr *MockConfigFactoryMockRecorder) RegisterProvider(providerType, factory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterProvider", reflect.TypeOf((*MockConfigFactory)(nil).RegisterProvider), providerType, factory)
}

// MockConfigManager is a mock of ConfigManager interface.
type MockConfigManager struct {
	ctrl     *gomock.Controller
	recorder *MockConfigManagerMockRecorder
	isgomock struct{}
}

// MockConfigManagerMockRecorder is the mock recorder for MockConfigManager.
type MockConfigManagerMockRecorder struct {
	mock *MockConfigManager
}

// NewMockConfigManager creates a new mock instance.
func NewMockConfigManager(ctrl *gomock.Controller) *MockConfigManager {
	mock := &MockConfigManager{ctrl: ctrl}
	mock.recorder = &MockConfigManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigManager) EXPECT() *MockConfigManagerMockRecorder {
	return m.recorder
}

// GetBool mocks base method.
func (m *MockConfigManager) GetBool(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBool", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetBool indicates an expected call of GetBool.
func (mr *MockConfigManagerMockRecorder) GetBool(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBool", reflect.TypeOf((*MockConfigManager)(nil).GetBool), key)
}

// GetDuration mocks base method.
func (m *MockConfigManager) GetDuration(key string) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDuration", key)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetDuration indicates an expected call of GetDuration.
func (mr *MockConfigManagerMockRecorder) GetDuration(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDuration", reflect.TypeOf((*MockConfigManager)(nil).GetDuration), key)
}

// GetFloat64 mocks base method.
func (m *MockConfigManager) GetFloat64(key string) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFloat64", key)
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetFloat64 indicates an expected call of GetFloat64.
func (mr *MockConfigManagerMockRecorder) GetFloat64(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloat64", reflect.TypeOf((*MockConfigManager)(nil).GetFloat64), key)
}

// GetInt mocks base method.
func (m *MockConfigManager) GetInt(key string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInt", key)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetInt indicates an expected call of GetInt.
func (mr *MockConfigManagerMockRecorder) GetInt(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInt", reflect.TypeOf((*MockConfigManager)(nil).GetInt), key)
}

// GetRaw mocks base method.
func (m *MockConfigManager) GetRaw() config.ConfigData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRaw")
	ret0, _ := ret[0].(config.ConfigData)
	return ret0
}

// GetRaw indicates an expected call of GetRaw.
func (mr *MockConfigManagerMockRecorder) GetRaw() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRaw", reflect.TypeOf((*MockConfigManager)(nil).GetRaw))
}

// GetString mocks base method.
func (m *MockConfigManager) GetString(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetString indicates an expected call of GetString.
func (mr *MockConfigManagerMockRecorder) GetString(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockConfigManager)(nil).GetString), key)
}

// GetStringSlice mocks base method.
func (m *MockConfigManager) GetStringSlice(key string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStringSlice", key)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetStringSlice indicates an expected call of GetStringSlice.
func (mr *MockConfigManagerMockRecorder) GetStringSlice(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStringSlice", reflect.TypeOf((*MockConfigManager)(nil).GetStringSlice), key)
}

// HasKey mocks base method.
func (m *MockConfigManager) HasKey(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasKey", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasKey indicates an expected call of HasKey.
func (mr *MockConfigManagerMockRecorder) HasKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasKey", reflect.TypeOf((*MockConfigManager)(nil).HasKey), key)
}

// LoadConfig mocks base method.
func (m *MockConfigManager) LoadConfig(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfig", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadConfig indicates an expected call of LoadConfig.
func (mr *MockConfigManagerMockRecorder) LoadConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfig", reflect.TypeOf((*MockConfigManager)(nil).LoadConfig), ctx)
}

// Reload mocks base method.
func (m *MockConfigManager) Reload(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reload", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reload indicates an expected call of Reload.
func (mr *MockConfigManagerMockRecorder) Reload(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reload", reflect.TypeOf((*MockConfigManager)(nil).Reload), ctx)
}

// Validate mocks base method.
func (m *MockConfigManager) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockConfigManagerMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockConfigManager)(nil).Validate))
}

// Watch mocks base method.
func (m *MockConfigManager) Watch(ctx context.Context, callback func()) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockConfigManagerMockRecorder) Watch(ctx, callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockConfigManager)(nil).Watch), ctx, callback)
}

// MockConfigValidator is a mock of ConfigValidator interface.
type MockConfigValidator struct {
	ctrl     *gomock.Controller
	recorder *MockConfigValidatorMockRecorder
	isgomock struct{}
}

// MockConfigValidatorMockRecorder is the mock recorder for MockConfigValidator.
type MockConfigValidatorMockRecorder struct {
	mock *MockConfigValidator
}

// NewMockConfigValidator creates a new mock instance.
func NewMockConfigValidator(ctrl *gomock.Controller) *MockConfigValidator {
	mock := &MockConfigValidator{ctrl: ctrl}
	mock.recorder = &MockConfigValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigValidator) EXPECT() *MockConfigValidatorMockRecorder {
	return m.recorder
}

// AddRule mocks base method.
func (m *MockConfigValidator) AddRule(rule config.ValidationRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRule", rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRule indicates an expected call of AddRule.
func (mr *MockConfigValidatorMockRecorder) AddRule(rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRule", reflect.TypeOf((*MockConfigValidator)(nil).AddRule), rule)
}

// GetRules mocks base method.
func (m *MockConfigValidator) GetRules() []config.ValidationRule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRules")
	ret0, _ := ret[0].([]config.ValidationRule)
	return ret0
}

// GetRules indicates an expected call of GetRules.
func (mr *MockConfigValidatorMockRecorder) GetRules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRules", reflect.TypeOf((*MockConfigValidator)(nil).GetRules))
}

// Validate mocks base method.
func (m *MockConfigValidator) Validate(data config.ConfigData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockConfigValidatorMockRecorder) Validate(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockConfigValidator)(nil).Validate), data)
}

// MockConfigWatcher is a mock of ConfigWatcher interface.
type MockConfigWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockConfigWatcherMockRecorder
	isgomock struct{}
}

// MockConfigWatcherMockRecorder is the mock recorder for MockConfigWatcher.
type MockConfigWatcherMockRecorder struct {
	mock *MockConfigWatcher
}

// NewMockConfigWatcher creates a new mock instance.
func NewMockConfigWatcher(ctrl *gomock.Controller) *MockConfigWatcher {
	mock := &MockConfigWatcher{ctrl: ctrl}
	mock.recorder = &MockConfigWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigWatcher) EXPECT() *MockConfigWatcherMockRecorder {
	return m.recorder
}

// AddCallback mocks base method.
func (m *MockConfigWatcher) AddCallback(callback func(config.ConfigData)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCallback", callback)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCallback indicates an expected call of AddCallback.
func (mr *MockConfigWatcherMockRecorder) AddCallback(callback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCallback", reflect.TypeOf((*MockConfigWatcher)(nil).AddCallback), callback)
}

// RemoveCallback mocks base method.
func (m *MockConfigWatcher) RemoveCallback(callbackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCallback", callbackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCallback indicates an expected call of RemoveCallback.
func (mr *MockConfigWatcherMockRecorder) RemoveCallback(callbackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCallback", reflect.TypeOf((*MockConfigWatcher)(nil).RemoveCallback), callbackID)
}

// Start mocks base method.
func (m *MockConfigWatcher) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockConfigWatcherMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockConfigWatcher)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockConfigWatcher) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockConfigWatcherMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockConfigWatcher)(nil).Stop))
}
