// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ai/llm/types.go
//
// Generated by this command:
//
//	mockgen -source=internal/ai/llm/types.go -destination=tests/mocks/llm_mocks.go -package=mocks -mock_names=HealthOperations=MockLLMHealthOperations
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	llm "github.com/EliasRanz/ai-code-gen/internal/ai/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMProvider is a mock of LLMProvider interface.
type MockLLMProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderMockRecorder
	isgomock struct{}
}

// MockLLMProviderMockRecorder is the mock recorder for MockLLMProvider.
type MockLLMProviderMockRecorder struct {
	mock *MockLLMProvider
}

// NewMockLLMProvider creates a new mock instance.
func NewMockLLMProvider(ctrl *gomock.Controller) *MockLLMProvider {
	mock := &MockLLMProvider{ctrl: ctrl}
	mock.recorder = &MockLLMProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProvider) EXPECT() *MockLLMProviderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockLLMProvider) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockLLMProviderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLLMProvider)(nil).Close))
}

// GenerateCode mocks base method.
func (m *MockLLMProvider) GenerateCode(ctx context.Context, req *llm.GenerationRequest) (*llm.GenerationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCode", ctx, req)
	ret0, _ := ret[0].(*llm.GenerationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCode indicates an expected call of GenerateCode.
func (mr *MockLLMProviderMockRecorder) GenerateCode(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCode", reflect.TypeOf((*MockLLMProvider)(nil).GenerateCode), ctx, req)
}

// GetLimits mocks base method.
func (m *MockLLMProvider) GetLimits() llm.ProviderLimits {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimits")
	ret0, _ := ret[0].(llm.ProviderLimits)
	return ret0
}

// GetLimits indicates an expected call of GetLimits.
func (mr *MockLLMProviderMockRecorder) GetLimits() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimits", reflect.TypeOf((*MockLLMProvider)(nil).GetLimits))
}

// GetProviderInfo mocks base method.
func (m *MockLLMProvider) GetProviderInfo() llm.ProviderInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderInfo")
	ret0, _ := ret[0].(llm.ProviderInfo)
	return ret0
}

// GetProviderInfo indicates an expected call of GetProviderInfo.
func (mr *MockLLMProviderMockRecorder) GetProviderInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderInfo", reflect.TypeOf((*MockLLMProvider)(nil).GetProviderInfo))
}

// HealthCheck mocks base method.
func (m *MockLLMProvider) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockLLMProviderMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockLLMProvider)(nil).HealthCheck), ctx)
}

// MockLLMGenerationOperations is a mock of LLMGenerationOperations interface.
type MockLLMGenerationOperations struct {
	ctrl     *gomock.Controller
	recorder *MockLLMGenerationOperationsMockRecorder
	isgomock struct{}
}

// MockLLMGenerationOperationsMockRecorder is the mock recorder for MockLLMGenerationOperations.
type MockLLMGenerationOperationsMockRecorder struct {
	mock *MockLLMGenerationOperations
}

// NewMockLLMGenerationOperations creates a new mock instance.
func NewMockLLMGenerationOperations(ctrl *gomock.Controller) *MockLLMGenerationOperations {
	mock := &MockLLMGenerationOperations{ctrl: ctrl}
	mock.recorder = &MockLLMGenerationOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMGenerationOperations) EXPECT() *MockLLMGenerationOperationsMockRecorder {
	return m.recorder
}

// GenerateCode mocks base method.
func (m *MockLLMGenerationOperations) GenerateCode(ctx context.Context, req *llm.GenerationRequest) (*llm.GenerationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCode", ctx, req)
	ret0, _ := ret[0].(*llm.GenerationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCode indicates an expected call of GenerateCode.
func (mr *MockLLMGenerationOperationsMockRecorder) GenerateCode(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCode", reflect.TypeOf((*MockLLMGenerationOperations)(nil).GenerateCode), ctx, req)
}

// MockLLMProviderOperations is a mock of LLMProviderOperations interface.
type MockLLMProviderOperations struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderOperationsMockRecorder
	isgomock struct{}
}

// MockLLMProviderOperationsMockRecorder is the mock recorder for MockLLMProviderOperations.
type MockLLMProviderOperationsMockRecorder struct {
	mock *MockLLMProviderOperations
}

// NewMockLLMProviderOperations creates a new mock instance.
func NewMockLLMProviderOperations(ctrl *gomock.Controller) *MockLLMProviderOperations {
	mock := &MockLLMProviderOperations{ctrl: ctrl}
	mock.recorder = &MockLLMProviderOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProviderOperations) EXPECT() *MockLLMProviderOperationsMockRecorder {
	return m.recorder
}

// GetLimits mocks base method.
func (m *MockLLMProviderOperations) GetLimits() llm.ProviderLimits {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimits")
	ret0, _ := ret[0].(llm.ProviderLimits)
	return ret0
}

// GetLimits indicates an expected call of GetLimits.
func (mr *MockLLMProviderOperationsMockRecorder) GetLimits() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimits", reflect.TypeOf((*MockLLMProviderOperations)(nil).GetLimits))
}

// GetProviderInfo mocks base method.
func (m *MockLLMProviderOperations) GetProviderInfo() llm.ProviderInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderInfo")
	ret0, _ := ret[0].(llm.ProviderInfo)
	return ret0
}

// GetProviderInfo indicates an expected call of GetProviderInfo.
func (mr *MockLLMProviderOperationsMockRecorder) GetProviderInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderInfo", reflect.TypeOf((*MockLLMProviderOperations)(nil).GetProviderInfo))
}

// MockLLMHealthOperations is a mock of HealthOperations interface.
type MockLLMHealthOperations struct {
	ctrl     *gomock.Controller
	recorder *MockLLMHealthOperationsMockRecorder
	isgomock struct{}
}

// MockLLMHealthOperationsMockRecorder is the mock recorder for MockLLMHealthOperations.
type MockLLMHealthOperationsMockRecorder struct {
	mock *MockLLMHealthOperations
}

// NewMockLLMHealthOperations creates a new mock instance.
func NewMockLLMHealthOperations(ctrl *gomock.Controller) *MockLLMHealthOperations {
	mock := &MockLLMHealthOperations{ctrl: ctrl}
	mock.recorder = &MockLLMHealthOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMHealthOperations) EXPECT() *MockLLMHealthOperationsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockLLMHealthOperations) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockLLMHealthOperationsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLLMHealthOperations)(nil).Close))
}

// HealthCheck mocks base method.
func (m *MockLLMHealthOperations) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockLLMHealthOperationsMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockLLMHealthOperations)(nil).HealthCheck), ctx)
}

// MockLLMFactory is a mock of LLMFactory interface.
type MockLLMFactory struct {
	ctrl     *gomock.Controller
	recorder *MockLLMFactoryMockRecorder
	isgomock struct{}
}

// MockLLMFactoryMockRecorder is the mock recorder for MockLLMFactory.
type MockLLMFactoryMockRecorder struct {
	mock *MockLLMFactory
}

// NewMockLLMFactory creates a new mock instance.
func NewMockLLMFactory(ctrl *gomock.Controller) *MockLLMFactory {
	mock := &MockLLMFactory{ctrl: ctrl}
	mock.recorder = &MockLLMFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMFactory) EXPECT() *MockLLMFactoryMockRecorder {
	return m.recorder
}

// CreateProvider mocks base method.
func (m *MockLLMFactory) CreateProvider(providerType string, config llm.ProviderConfig) (llm.LLMProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProvider", providerType, config)
	ret0, _ := ret[0].(llm.LLMProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProvider indicates an expected call of CreateProvider.
func (mr *MockLLMFactoryMockRecorder) CreateProvider(providerType, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProvider", reflect.TypeOf((*MockLLMFactory)(nil).CreateProvider), providerType, config)
}

// ListAvailableProviders mocks base method.
func (m *MockLLMFactory) ListAvailableProviders() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailableProviders")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ListAvailableProviders indicates an expected call of ListAvailableProviders.
func (mr *MockLLMFactoryMockRecorder) ListAvailableProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailableProviders", reflect.TypeOf((*MockLLMFactory)(nil).ListAvailableProviders))
}

// MockRateLimiter is a mock of RateLimiter interface.
type MockRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRateLimiterMockRecorder
	isgomock struct{}
}

// MockRateLimiterMockRecorder is the mock recorder for MockRateLimiter.
type MockRateLimiterMockRecorder struct {
	mock *MockRateLimiter
}

// NewMockRateLimiter creates a new mock instance.
func NewMockRateLimiter(ctrl *gomock.Controller) *MockRateLimiter {
	mock := &MockRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateLimiter) EXPECT() *MockRateLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockRateLimiter) Allow(userID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", userID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Allow indicates an expected call of Allow.
func (mr *MockRateLimiterMockRecorder) Allow(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockRateLimiter)(nil).Allow), userID)
}

// MockQuotaManager is a mock of QuotaManager interface.
type MockQuotaManager struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaManagerMockRecorder
	isgomock struct{}
}

// MockQuotaManagerMockRecorder is the mock recorder for MockQuotaManager.
type MockQuotaManagerMockRecorder struct {
	mock *MockQuotaManager
}

// NewMockQuotaManager creates a new mock instance.
func NewMockQuotaManager(ctrl *gomock.Controller) *MockQuotaManager {
	mock := &MockQuotaManager{ctrl: ctrl}
	mock.recorder = &MockQuotaManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaManager) EXPECT() *MockQuotaManagerMockRecorder {
	return m.recorder
}

// IncrementUsage mocks base method.
func (m *MockQuotaManager) IncrementUsage(userID string, tokens int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUsage", userID, tokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUsage indicates an expected call of IncrementUsage.
func (mr *MockQuotaManagerMockRecorder) IncrementUsage(userID, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUsage", reflect.TypeOf((*MockQuotaManager)(nil).IncrementUsage), userID, tokens)
}

// IsQuotaExceeded mocks base method.
func (m *MockQuotaManager) IsQuotaExceeded(userID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsQuotaExceeded", userID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsQuotaExceeded indicates an expected call of IsQuotaExceeded.
func (mr *MockQuotaManagerMockRecorder) IsQuotaExceeded(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsQuotaExceeded", reflect.TypeOf((*MockQuotaManager)(nil).IsQuotaExceeded), userID)
}
