// Code generated by MockGen. DO NOT EDIT.
// Source: internal/utilities/repository_template.go
//
// Generated by this command:
//
//	mockgen -source=internal/utilities/repository_template.go -destination=tests/mocks/utilities_template_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	utilities "github.com/EliasRanz/ai-code-gen/internal/utilities"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsCollector is a mock of MetricsCollector interface.
type MockMetricsCollector struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCollectorMockRecorder
	isgomock struct{}
}

// MockMetricsCollectorMockRecorder is the mock recorder for MockMetricsCollector.
type MockMetricsCollectorMockRecorder struct {
	mock *MockMetricsCollector
}

// NewMockMetricsCollector creates a new mock instance.
func NewMockMetricsCollector(ctrl *gomock.Controller) *MockMetricsCollector {
	mock := &MockMetricsCollector{ctrl: ctrl}
	mock.recorder = &MockMetricsCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsCollector) EXPECT() *MockMetricsCollectorMockRecorder {
	return m.recorder
}

// IncrementCounter mocks base method.
func (m *MockMetricsCollector) IncrementCounter(name string, labels map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementCounter", name, labels)
}

// IncrementCounter indicates an expected call of IncrementCounter.
func (mr *MockMetricsCollectorMockRecorder) IncrementCounter(name, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockMetricsCollector)(nil).IncrementCounter), name, labels)
}

// RecordHistogram mocks base method.
func (m *MockMetricsCollector) RecordHistogram(name string, value float64, labels map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordHistogram", name, value, labels)
}

// RecordHistogram indicates an expected call of RecordHistogram.
func (mr *MockMetricsCollectorMockRecorder) RecordHistogram(name, value, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHistogram", reflect.TypeOf((*MockMetricsCollector)(nil).RecordHistogram), name, value, labels)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// ErrorContext mocks base method.
func (m *MockLogger) ErrorContext(ctx context.Context, msg string, fields ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorContext", varargs...)
}

// ErrorContext indicates an expected call of ErrorContext.
func (mr *MockLoggerMockRecorder) ErrorContext(ctx, msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorContext", reflect.TypeOf((*MockLogger)(nil).ErrorContext), varargs...)
}

// InfoContext mocks base method.
func (m *MockLogger) InfoContext(ctx context.Context, msg string, fields ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoContext", varargs...)
}

// InfoContext indicates an expected call of InfoContext.
func (mr *MockLoggerMockRecorder) InfoContext(ctx, msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoContext", reflect.TypeOf((*MockLogger)(nil).InfoContext), varargs...)
}

// WarnContext mocks base method.
func (m *MockLogger) WarnContext(ctx context.Context, msg string, fields ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnContext", varargs...)
}

// WarnContext indicates an expected call of WarnContext.
func (mr *MockLoggerMockRecorder) WarnContext(ctx, msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnContext", reflect.TypeOf((*MockLogger)(nil).WarnContext), varargs...)
}

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockDatabase) BeginTx(ctx context.Context) (utilities.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(utilities.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockDatabaseMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockDatabase)(nil).BeginTx), ctx)
}

// Close mocks base method.
func (m *MockDatabase) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatabaseMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatabase)(nil).Close))
}

// HealthCheck mocks base method.
func (m *MockDatabase) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockDatabaseMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockDatabase)(nil).HealthCheck), ctx)
}

// MockQueryOperation is a mock of QueryOperation interface.
type MockQueryOperation struct {
	ctrl     *gomock.Controller
	recorder *MockQueryOperationMockRecorder
	isgomock struct{}
}

// MockQueryOperationMockRecorder is the mock recorder for MockQueryOperation.
type MockQueryOperationMockRecorder struct {
	mock *MockQueryOperation
}

// NewMockQueryOperation creates a new mock instance.
func NewMockQueryOperation(ctrl *gomock.Controller) *MockQueryOperation {
	mock := &MockQueryOperation{ctrl: ctrl}
	mock.recorder = &MockQueryOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryOperation) EXPECT() *MockQueryOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockQueryOperation) Execute(ctx context.Context, db utilities.Database) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, db)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockQueryOperationMockRecorder) Execute(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockQueryOperation)(nil).Execute), ctx, db)
}

// MockBatchOperation is a mock of BatchOperation interface.
type MockBatchOperation struct {
	ctrl     *gomock.Controller
	recorder *MockBatchOperationMockRecorder
	isgomock struct{}
}

// MockBatchOperationMockRecorder is the mock recorder for MockBatchOperation.
type MockBatchOperationMockRecorder struct {
	mock *MockBatchOperation
}

// NewMockBatchOperation creates a new mock instance.
func NewMockBatchOperation(ctrl *gomock.Controller) *MockBatchOperation {
	mock := &MockBatchOperation{ctrl: ctrl}
	mock.recorder = &MockBatchOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchOperation) EXPECT() *MockBatchOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockBatchOperation) Execute(ctx context.Context, db utilities.Database) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, db)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockBatchOperationMockRecorder) Execute(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockBatchOperation)(nil).Execute), ctx, db)
}

// MockRepositoryTemplate is a mock of RepositoryTemplate interface.
type MockRepositoryTemplate struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryTemplateMockRecorder
	isgomock struct{}
}

// MockRepositoryTemplateMockRecorder is the mock recorder for MockRepositoryTemplate.
type MockRepositoryTemplateMockRecorder struct {
	mock *MockRepositoryTemplate
}

// NewMockRepositoryTemplate creates a new mock instance.
func NewMockRepositoryTemplate(ctrl *gomock.Controller) *MockRepositoryTemplate {
	mock := &MockRepositoryTemplate{ctrl: ctrl}
	mock.recorder = &MockRepositoryTemplateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryTemplate) EXPECT() *MockRepositoryTemplateMockRecorder {
	return m.recorder
}

// AfterOperation mocks base method.
func (m *MockRepositoryTemplate) AfterOperation(ctx context.Context, operation utilities.OperationType, result any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AfterOperation", ctx, operation, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// AfterOperation indicates an expected call of AfterOperation.
func (mr *MockRepositoryTemplateMockRecorder) AfterOperation(ctx, operation, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterOperation", reflect.TypeOf((*MockRepositoryTemplate)(nil).AfterOperation), ctx, operation, result)
}

// BeforeOperation mocks base method.
func (m *MockRepositoryTemplate) BeforeOperation(ctx context.Context, operation utilities.OperationType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeforeOperation", ctx, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// BeforeOperation indicates an expected call of BeforeOperation.
func (mr *MockRepositoryTemplateMockRecorder) BeforeOperation(ctx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeOperation", reflect.TypeOf((*MockRepositoryTemplate)(nil).BeforeOperation), ctx, operation)
}

// ExecuteBatch mocks base method.
func (m *MockRepositoryTemplate) ExecuteBatch(ctx context.Context, operations []utilities.BatchOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteBatch", ctx, operations)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteBatch indicates an expected call of ExecuteBatch.
func (mr *MockRepositoryTemplateMockRecorder) ExecuteBatch(ctx, operations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteBatch", reflect.TypeOf((*MockRepositoryTemplate)(nil).ExecuteBatch), ctx, operations)
}

// ExecuteQuery mocks base method.
func (m *MockRepositoryTemplate) ExecuteQuery(ctx context.Context, query utilities.QueryOperation) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQuery", ctx, query)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockRepositoryTemplateMockRecorder) ExecuteQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockRepositoryTemplate)(nil).ExecuteQuery), ctx, query)
}

// ExecuteWithTransaction mocks base method.
func (m *MockRepositoryTemplate) ExecuteWithTransaction(ctx context.Context, operation utilities.TransactionOperation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWithTransaction", ctx, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteWithTransaction indicates an expected call of ExecuteWithTransaction.
func (mr *MockRepositoryTemplateMockRecorder) ExecuteWithTransaction(ctx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWithTransaction", reflect.TypeOf((*MockRepositoryTemplate)(nil).ExecuteWithTransaction), ctx, operation)
}

// OnError mocks base method.
func (m *MockRepositoryTemplate) OnError(ctx context.Context, operation utilities.OperationType, err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnError", ctx, operation, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnError indicates an expected call of OnError.
func (mr *MockRepositoryTemplateMockRecorder) OnError(ctx, operation, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnError", reflect.TypeOf((*MockRepositoryTemplate)(nil).OnError), ctx, operation, err)
}
