server:
  port: 8080
  host: "0.0.0.0"
  
database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "ai_ui_generator"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

auth:
  jwt_secret: "your-jwt-secret-key"
  jwt_expiry: "24h"
  oauth:
    google:
      client_id: "your-google-client-id"
      client_secret: "your-google-client-secret"
      redirect_url: "http://localhost:3000/api/auth/callback/google"

ai:
  llm_endpoint: "http://localhost:8000/v1"
  model_name: "gpt-3.5-turbo"
  max_tokens: 4096
  temperature: 0.7

logging:
  level: "info"
  format: "json"

observability:
  metrics_enabled: true
  tracing_enabled: true
  jaeger_endpoint: "http://localhost:14268/api/traces"
