// Package user contains consolidated user business logic and use cases
package user

import (
	"context"
	"fmt"

	"github.com/EliasRanz/ai-code-gen/internal/utilities"
)

// Use Cases - Consolidated from application layer

// UserCreator handles user creation business logic
type UserCreator struct {
	userRepo  Repository
	validator Validator
	notifier  NotificationService
}

// NewUserCreator creates a new instance of UserCreator
func NewUserCreator(
	userRepo Repository,
	validator Validator,
	notifier NotificationService,
) *UserCreator {
	return &UserCreator{
		userRepo:  userRepo,
		validator: validator,
		notifier:  notifier,
	}
}

// CreateUserRequest represents the input for creating a user
type CreateUserRequest struct {
	Email     string   `json:"email" validate:"required,email"`
	Name      string   `json:"name" validate:"required,min=2,max=100"`
	AvatarURL string   `json:"avatar_url" validate:"omitempty,url"`
	Roles     []string `json:"roles" validate:"dive,oneof=admin user viewer"`
	// Password removed - handled by Auth Service
}

// CreateUserResponse represents the output of user creation
type CreateUserResponse struct {
	User *User `json:"user"`
}

// Execute performs the user creation use case
func (uc *UserCreator) Execute(ctx context.Context, req CreateUserRequest) (*CreateUserResponse, error) {
	// Validate input
	if err := uc.validator.ValidateStruct(req); err != nil {
		return nil, utilities.NewValidationError("invalid user data", err)
	}

	// Check if user already exists
	existing, err := uc.userRepo.GetByEmail(ctx, req.Email)
	if err != nil && !utilities.IsNotFoundError(err) {
		return nil, fmt.Errorf("failed to check existing user: %w", err)
	}
	if existing.ID != "" {
		return nil, utilities.NewConflictError("user with this email already exists")
	}

	// Create user entity (ID will be auto-generated by repository)
	userEntity := User{
		Email:     req.Email,
		Name:      req.Name,
		AvatarURL: req.AvatarURL,
		Roles:     req.Roles,
		Role:      RoleUser, // Default role
		Active:    true,
		Status:    StatusActiveUser,
	}

	// Validate user entity
	if err := uc.validator.ValidateUser(&userEntity); err != nil {
		return nil, utilities.NewValidationError("invalid user entity", err)
	}

	// Store user
	if err := uc.userRepo.Create(ctx, userEntity); err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	// Notify user created (async, don't block on failure)
	go func() {
		if err := uc.notifier.NotifyUserCreated(context.Background(), &userEntity); err != nil {
			// Log error but don't fail the operation
		}
	}()

	return &CreateUserResponse{
		User: &userEntity,
	}, nil
}

// UserRetriever handles user retrieval business logic
type UserRetriever struct {
	userRepo Repository
}

// NewUserRetriever creates a new instance of UserRetriever
func NewUserRetriever(userRepo Repository) *UserRetriever {
	return &UserRetriever{
		userRepo: userRepo,
	}
}

// GetUserRequest represents the input for getting a user
type GetUserRequest struct {
	UserID utilities.UserID `json:"user_id" validate:"required"`
}

// GetUserResponse represents the output of user retrieval
type GetUserResponse struct {
	User *User `json:"user"`
}

// Execute performs the user retrieval use case
func (uc *UserRetriever) Execute(ctx context.Context, req GetUserRequest) (*GetUserResponse, error) {
	if req.UserID == "" {
		return nil, utilities.NewValidationError("user ID required", fmt.Errorf("user ID cannot be empty"))
	}

	user, err := uc.userRepo.GetByID(ctx, req.UserID)
	if err != nil {
		return nil, utilities.NewNotFoundError("user not found")
	}

	return &GetUserResponse{
		User: &user,
	}, nil
}

// UserUpdater handles user update business logic
type UserUpdater struct {
	userRepo  Repository
	validator Validator
	notifier  NotificationService
}

// NewUserUpdater creates a new instance of UserUpdater
func NewUserUpdater(
	userRepo Repository,
	validator Validator,
	notifier NotificationService,
) *UserUpdater {
	return &UserUpdater{
		userRepo:  userRepo,
		validator: validator,
		notifier:  notifier,
	}
}

// UpdateUserRequest represents the input for updating a user
type UpdateUserRequest struct {
	UserID    utilities.UserID `json:"user_id" validate:"required"`
	Name      *string          `json:"name,omitempty" validate:"omitempty,min=2,max=100"`
	AvatarURL *string          `json:"avatar_url,omitempty" validate:"omitempty,url"`
	Role      *Role            `json:"role,omitempty" validate:"omitempty,oneof=user admin"`
	Active    *bool            `json:"active,omitempty"`
	Status    *UserStatus      `json:"status,omitempty" validate:"omitempty,oneof=active inactive suspended"`
}

// UpdateUserResponse represents the output of user update
type UpdateUserResponse struct {
	User *User `json:"user"`
}

// Execute performs the user update use case
func (uc *UserUpdater) Execute(ctx context.Context, req UpdateUserRequest) (*UpdateUserResponse, error) {
	// Validate input
	if err := uc.validator.ValidateStruct(req); err != nil {
		return nil, utilities.NewValidationError("invalid update data", err)
	}

	// Get existing user
	existingUser, err := uc.userRepo.GetByID(ctx, req.UserID)
	if err != nil {
		return nil, utilities.NewNotFoundError("user not found")
	}

	// Apply updates
	if req.Name != nil {
		existingUser.Name = *req.Name
	}
	if req.AvatarURL != nil {
		existingUser.AvatarURL = *req.AvatarURL
	}
	if req.Role != nil {
		existingUser.Role = *req.Role
	}
	if req.Active != nil {
		existingUser.Active = *req.Active
	}
	if req.Status != nil {
		existingUser.Status = *req.Status
	}

	// Validate updated user
	if err := uc.validator.ValidateUser(&existingUser); err != nil {
		return nil, utilities.NewValidationError("invalid user data", err)
	}

	// Update user
	if err := uc.userRepo.Update(ctx, existingUser); err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	// Notify user updated
	if err := uc.notifier.NotifyUserUpdated(ctx, &existingUser); err != nil {
		// Log error but don't fail the operation
	}

	return &UpdateUserResponse{
		User: &existingUser,
	}, nil
}

// UserDeleter handles user deletion business logic
type UserDeleter struct {
	userRepo Repository
	notifier NotificationService
}

// NewUserDeleter creates a new instance of UserDeleter
func NewUserDeleter(
	userRepo Repository,
	notifier NotificationService,
) *UserDeleter {
	return &UserDeleter{
		userRepo: userRepo,
		notifier: notifier,
	}
}

// DeleteUserRequest represents the input for deleting a user
type DeleteUserRequest struct {
	UserID utilities.UserID `json:"user_id" validate:"required"`
}

// DeleteUserResponse represents the output of user deletion
type DeleteUserResponse struct {
	Success bool `json:"success"`
}

// Execute performs the user deletion use case
func (uc *UserDeleter) Execute(ctx context.Context, req DeleteUserRequest) (*DeleteUserResponse, error) {
	if req.UserID == "" {
		return nil, utilities.NewValidationError("user ID required", fmt.Errorf("user ID cannot be empty"))
	}

	// Check if user exists
	_, err := uc.userRepo.GetByID(ctx, req.UserID)
	if err != nil {
		return nil, utilities.NewNotFoundError("user not found")
	}

	// Delete user
	if err := uc.userRepo.Delete(ctx, req.UserID); err != nil {
		return nil, fmt.Errorf("failed to delete user: %w", err)
	}

	// Notify user deleted
	if err := uc.notifier.NotifyUserDeleted(ctx, req.UserID); err != nil {
		// Log error but don't fail the operation
	}

	return &DeleteUserResponse{
		Success: true,
	}, nil
}

// UserLister handles user listing business logic
type UserLister struct {
	userRepo Repository
}

// NewUserLister creates a new instance of UserLister
func NewUserLister(userRepo Repository) *UserLister {
	return &UserLister{
		userRepo: userRepo,
	}
}

// ListUsersRequest represents the input for listing users
type ListUsersRequest struct {
	Page   int32  `json:"page" validate:"min=1"`
	Limit  int32  `json:"limit" validate:"min=1,max=100"`
	Search string `json:"search,omitempty"`
}

// ListUsersResponse represents the output of user listing
type ListUsersResponse struct {
	Users []User `json:"users"`
	Total int    `json:"total"`
	Page  int    `json:"page"`
	Limit int    `json:"limit"`
}

// Execute performs the user listing use case
func (uc *UserLister) Execute(ctx context.Context, req ListUsersRequest) (*ListUsersResponse, error) {
	// Set defaults
	if req.Page == 0 {
		req.Page = 1
	}
	if req.Limit == 0 {
		req.Limit = 10
	}

	// Create pagination params
	params := utilities.PaginationParams{
		Page:  int32(req.Page),
		Limit: int32(req.Limit),
	}

	// Get users
	users, err := uc.userRepo.List(ctx, params, req.Search)
	if err != nil {
		return nil, fmt.Errorf("failed to list users: %w", err)
	}

	// Get total count
	total, err := uc.userRepo.Count(ctx, req.Search)
	if err != nil {
		return nil, fmt.Errorf("failed to count users: %w", err)
	}

	return &ListUsersResponse{
		Users: users,
		Total: total,
		Page:  int(req.Page),
		Limit: int(req.Limit),
	}, nil
}
